import React from "react"
import type { NextPage } from "next"
import Head from "next/head"
import TodoList from "../components/Todolist"


const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="p-20 text-center">
                <TodoList />
            </main>

            <footer className="p-5 text-center border-t text-sm">
                A todo list created by Recoil.
            </footer>
        </div>
    )
}

export default Home
