import React from "react"
import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="p-20 text-center">
                <h1 className="text-5xl font-bold">
                    Welcome to <a href="https://nextjs.org" className="text-blue-500">Next.js!</a>
                </h1>

                <p className="mt-10 text-lg">
                    Get started by editing{" "}
                    <code>pages/index.tsx</code>
                </p>

                <div className="mt-10 max-w-xl m-auto grid grid-cols-2 gap-4 text-left">
                    <a
                        href="https://nextjs.org/docs"
                        className="block border p-5"
                    >
                        <h2 className="text-xl font-bold">Documentation &rarr;</h2>
                        <p className="mt-4">Find in-depth information about Next.js features and API.</p>
                    </a>

                    <a
                        href="https://nextjs.org/learn"
                        className="block border p-5"
                    >
                        <h2 className="text-xl font-bold">Learn &rarr;</h2>
                        <p className="mt-4">Learn about Next.js in an interactive course with quizzes!</p>
                    </a>

                    <a
                        href="https://github.com/vercel/next.js/tree/canary/examples"
                        className="block border p-5"
                    >
                        <h2 className="text-xl font-bold">Examples &rarr;</h2>
                        <p className="mt-4">Discover and deploy boilerplate example Next.js projects.</p>
                    </a>

                    <a
                        href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        className="block border p-5"
                    >
                        <h2 className="text-xl font-bold">Deploy &rarr;</h2>
                        <p className="mt-4">
                            Instantly deploy your Next.js site to a public URL with Vercel.
                        </p>
                    </a>
                </div>
            </main>

            <footer className="p-5 text-center border-t text-sm">
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{" "}
                    <span>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    )
}

export default Home
